COLORS = {
    "ROLLOUT": "violet",
    "ROLLOUT_PROB": "violet",
    "RANDOM": "dodgerblue",
    "GREEDY": "orangered",
    "REDO": "limegreen",
}

AA_NAMES_TEMPEST = [
    "dl_alanine_75x",
    "l_arginine_75x",
    "l_asparagine_75x",
    "l_aspartic_acid_40x",
    "l_cysteine_75x",
    "l_glutamic_acid_75x",
    "l_glutamine_75x",
    "glycine_75x",
    "l_histidine_75x",
    "l_isoleucine_75x",
    "l_leucine_75x",
    "l_lysine_75x",
    "l_methionine_75x",
    "l_phenylalanine_75x",
    "prolines_75x",
    "l_serine_75x",
    "l_threonine_75x",
    "l_tryptophan_75x",
    "l_tyrosine_75x",
    "l_valine_75x",
]

AA_NAMES_2 = [
    "dl_alanine_100x",
    "l_arginine_100x",
    "l_asparagine_100x",
    "l_aspartic_acid_45x",
    "l_cysteine_100x",
    "l_glutamic_acid_75x",
    "l_glutamine_100x",
    "glycine_100x",
    "l_histidine_100x",
    "l_isoleucine_100x",
    "l_leucine_100x",
    "l_lysine_100x",
    "l_methionine_100x",
    "l_phenylalanine_100x",
    "prolines_100x",
    "l_serine_100x",
    "l_threonine_100x",
    "l_tryptophan_100x",
    "l_tyrosine_100x",
    "l_valine_100x",
]

AA_SHORT = [
    "ala",
    "arg",
    "asn",
    "asp",
    "cys",
    "glu",
    "gln",
    "gly",
    "his",
    "ile",
    "leu",
    "lys",
    "met",
    "phe",
    "pro",
    "ser",
    "thr",
    "trp",
    "tyr",
    "val",
]

AA_SHORT_NOTS = [
    "~ala",
    "~arg",
    "~asn",
    "~asp",
    "~cys",
    "~glu",
    "~gln",
    "~gly",
    "~his",
    "~ile",
    "~leu",
    "~lys",
    "~met",
    "~phe",
    "~pro",
    "~ser",
    "~thr",
    "~trp",
    "~tyr",
    "~val",
]


BASE_NAMES = [
    "adenine",
    "biotin",
    "d_glucose",
    "folic_acid",
    "guanine",
    "irons",
    "magnesium_sulfate",
    "manganese_sulfate",
    "nadp",
    "niacinamide",
    "paba",
    "pantothenate",
    "pyridoxal",
    "pyridoxamine",
    "riboflavin",
    "sodium_acetate",
    "thiamine",
    "uracil",
    "vitamin_b12",
]

BASE_NAMES_NOTS = [
    "~adenine",
    "~biotin",
    "~d_glucose",
    "~folic_acid",
    "~guanine",
    "~irons",
    "~magnesium_sulfate",
    "~manganese_sulfate",
    "~nadp",
    "~niacinamide",
    "~paba",
    "~pantothenate",
    "~pyridoxal",
    "~pyridoxamine",
    "~riboflavin",
    "~sodium_acetate",
    "~thiamine",
    "~uracil",
    "~vitamin_b12",
]

BASE_NAMES_TEMPEST = [
    "adenine_80x",
    "biotin_80x",
    "d_glucose_20x",
    "folic_acid_80x",
    "guanine_80x",
    "irons_80x",
    "magnesium_sulfate_80x",
    "manganese_sulfate_80x",
    "nadp_80x",
    "niacinamide_80x",
    "paba_80x",
    "pantothenate_80x",
    "pyridoxal_80x",
    "pyridoxamine_80x",
    "riboflavin_20x",
    "sodium_acetate_80x",
    "thiamine_80x",
    "uracil_80x",
    "vitamin_b12_80x",
]